development:
  :address: smtp.server.com
  :port: 25
  :authentication: plain
  :user_name: user
  :password: pass
production:
  :address: mail.qondaaficionados.mx
  :port: 25
  :authentication: plain
  :user_name: qonda@qondaaficionados.mx
  :password: milenio