development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: qondaaficionados@decisionesinteligentes.com
  :password: 476X77
  :enable_starttls_auto: true
  :tls: true
  :domain: decisionesinteligentes.com
production:
    :address: smtp.gmail.com
    :port: 587
    :authentication: plain
    :user_name: qondaaficionados@decisionesinteligentes.com
    :password: 476X77
    :enable_starttls_auto: true
    :tls: true
    :domain: decisionesinteligentes.com